#!/usr/bin/env python3
# scripts/sync-shims.py
#
# 把 .agent/ 下的真理源内联编译成各 IDE 的 shim 文件。
# Python 版：避免 shell 脚本在沙箱下因拉起子进程（cat）而被拦截的问题。

import os
import sys

# 确定项目根目录
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
os.chdir(project_root)

CHECK_MODE = "--check" in sys.argv

HEADER_LINES = [
    "<!-- AUTO-GENERATED by scripts/sync-shims.sh - DO NOT EDIT -->",
    "<!-- Edit canonical files in .agent/ then run: bash scripts/sync-shims.sh -->"
]

INJECTION_MARKER = "<!-- AUTO-GENERATED SHIMS START - DO NOT EDIT BELOW -->"

def print_header():
    return "\n".join(HEADER_LINES) + "\n\n"

def emit(output_path, front_matter_lines, sources):
    output_content = ""
    # 前额数据
    if front_matter_lines:
        output_content += "\n".join(front_matter_lines) + "\n"
    
    output_content += print_header()
    
    # 源文件内容拼接
    parts = []
    for src in sources:
        if not os.path.exists(src):
            continue
        with open(src, "r", encoding="utf-8") as f:
            parts.append(f.read())
    
    output_content += "\n---\n\n".join(parts)
    
    # 确保父目录存在
    parent_dir = os.path.dirname(output_path)
    if parent_dir and not os.path.exists(parent_dir):
        os.makedirs(parent_dir, exist_ok=True)
        
    if CHECK_MODE:
        if not os.path.exists(output_path):
            return True # Drift detected
        with open(output_path, "r", encoding="utf-8") as f:
            current = f.read()
        return current != output_content
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output_content)
        print(f"  wrote {output_path}")
        return False

def emit_skill(slug, description, src_path):
    output_path = f".kiro/skills/{slug}/SKILL.md"
    front_matter = [
        "---",
        f"name: {slug}",
        f"description: {description}",
        "---"
    ]
    output_content = "\n".join(front_matter) + "\n" + print_header()
    
    if os.path.exists(src_path):
        with open(src_path, "r", encoding="utf-8") as f:
            output_content += f.read()
            
    parent_dir = os.path.dirname(output_path)
    if parent_dir and not os.path.exists(parent_dir):
        os.makedirs(parent_dir, exist_ok=True)
        
    if CHECK_MODE:
        if not os.path.exists(output_path):
            return True
        with open(output_path, "r", encoding="utf-8") as f:
            current = f.read()
        return current != output_content
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output_content)
        print(f"  wrote {output_path}")
        return False

def main():
    drift = False
    
    print("[sync] Kiro skills...")
    drift |= emit_skill("pbt-cookbook", "Property-based testing reference. Load when writing or reviewing PBTs (*.pbt.ts files), designing invariants, or evaluating round-trip / idempotency / commutativity properties.", ".agent/skills/pbt-cookbook.md")
    drift |= emit_skill("frontend-patterns", "Frontend layered architecture patterns (tokens/primitives/composites/features/pages). Load when building or refactoring UI components in packages/ui-* or apps/*, deciding which layer something belongs in, or untangling layer violations.", ".agent/skills/frontend-patterns.md")
    drift |= emit_skill("state-machines", "UI state machine design (XState-style). Load when designing complex interaction flows, multi-step wizards, async operations with cancellation/retry, or when a feature has more than ~3 mutually exclusive view states.", ".agent/skills/state-machines.md")
    drift |= emit_skill("design-tokens", "Design tokens (DTCG format). Load when editing shared/tokens/*, proposing new semantic tokens, refactoring inline color/spacing/typography values, or auditing visual consistency.", ".agent/skills/design-tokens.md")
    
    print("[sync] Kiro steering...")
    # 0) 清理旧 steering
    if not CHECK_MODE:
        for f in [".kiro/steering/00-core.md", ".kiro/steering/10-domain-and-adr-index.md"]:
            if os.path.exists(f):
                os.remove(f)
                
    drift |= emit(".kiro/steering/00-discipline.md", ["---", "inclusion: always", "---", ""], [".agent/skills/agent-discipline.md"])
    drift |= emit(".kiro/steering/01-philosophy.md", ["---", "inclusion: always", "---", ""], [".agent/core/philosophy.md"])
    drift |= emit(".kiro/steering/02-conventions.md", ["---", "inclusion: always", "---", ""], [".agent/core/conventions.md"])
    drift |= emit(".kiro/steering/03-boundaries.md", ["---", "inclusion: always", "---", ""], [".agent/core/boundaries.md"])
    drift |= emit(".kiro/steering/04-glossary.md", ["---", "inclusion: always", "---", ""], [".agent/core/glossary.md"])
    drift |= emit(".kiro/steering/04b-design-system.md", ["---", "inclusion: always", "---", ""], [".agent/core/design-system.md"])
    
    indexes_src = [
        ".agent/adr/_index.md", ".agent/flows/_index.md",
        ".agent/sub-agents/_index.md", ".agent/workflows/_index.md",
        ".agent/skills/_index.md", ".agent/legacy/_index.md"
    ]
    drift |= emit(".kiro/steering/05-indexes.md", ["---", "inclusion: always", "---", ""], indexes_src)
    
    print("[sync] Cursor rules...")
    if not CHECK_MODE:
        for f in [".cursor/rules/00-core.mdc", ".cursor/rules/10-domain.mdc"]:
            if os.path.exists(f):
                os.remove(f)
                
    drift |= emit(".cursor/rules/00-discipline.mdc", ["---", "description: Agent behavioral discipline (auto-generated)", "alwaysApply: true", "---", ""], [".agent/skills/agent-discipline.md"])
    drift |= emit(".cursor/rules/01-philosophy.mdc", ["---", "description: Product philosophy (auto-generated)", "alwaysApply: true", "---", ""], [".agent/core/philosophy.md"])
    drift |= emit(".cursor/rules/02-conventions.mdc", ["---", "description: Code & workflow conventions (auto-generated)", "alwaysApply: true", "---", ""], [".agent/core/conventions.md"])
    drift |= emit(".cursor/rules/03-boundaries.mdc", ["---", "description: Module boundaries (auto-generated)", "alwaysApply: true", "---", ""], [".agent/core/boundaries.md"])
    drift |= emit(".cursor/rules/04-glossary.mdc", ["---", "description: Glossary (auto-generated)", "alwaysApply: true", "---", ""], [".agent/core/glossary.md"])
    drift |= emit(".cursor/rules/05-indexes.mdc", ["---", "description: Indexes of ADR/flow/sub-agents/workflows/skills/legacy (auto-generated)", "alwaysApply: true", "---", ""], indexes_src)
    
    print("[sync] Antigravity (Root AGENTS.md)...")
    antigravity_src = [
        ".agent/skills/agent-discipline.md",
        ".agent/core/philosophy.md",
        ".agent/core/conventions.md",
        ".agent/core/boundaries.md"
    ]
    
    # 拼接所有的 shim 规则内容
    shim_content = print_header()
    parts = []
    for src in antigravity_src:
        if os.path.exists(src):
            with open(src, "r", encoding="utf-8") as f:
                parts.append(f.read())
    shim_content += "\n---\n\n".join(parts)
    
    # 读取原始的 AGENTS.md
    agents_path = "AGENTS.md"
    if os.path.exists(agents_path):
        with open(agents_path, "r", encoding="utf-8") as f:
            original_agents = f.read()
    else:
        original_agents = ""
        
    # 根据 marker 拆分出 base content
    if INJECTION_MARKER in original_agents:
        base_content = original_agents.split(INJECTION_MARKER)[0].rstrip()
    else:
        base_content = original_agents.rstrip()
        
    final_agents_content = base_content + "\n\n" + INJECTION_MARKER + "\n\n" + shim_content
    
    if CHECK_MODE:
        if original_agents != final_agents_content:
            drift = True
    else:
        with open(agents_path, "w", encoding="utf-8") as f:
            f.write(final_agents_content)
        print(f"  wrote {agents_path}")
        
    print("[sync] Claude Code CLAUDE.md...")
    drift |= emit(".claude/CLAUDE.md", [], [agents_path])
    
    print("[sync] Antigravity .antigravity/AGENTS.md (Mirror)...")
    drift |= emit(".antigravity/AGENTS.md", [], [agents_path])
    
    if CHECK_MODE:
        if drift:
            print("[sync] DRIFT detected. Run: python3 scripts/sync-shims.py && git add .")
            sys.exit(1)
        else:
            print("[sync] OK - all shims in sync.")
            sys.exit(0)
    else:
        print("[sync] Done. All IDE shims compiled.")

if __name__ == "__main__":
    main()
